### ISSUE TITLE
Cannot find module 'lodash.sortby'

### ISSUE THREAD

**Issue by ChanEilFhios** [nknapp/analyze-module-size#4]
First, thank you for your work on this. It looks very useful.

I installed and ran but got the above error. It appears that lodash.sortby is a devDependency in your package.json but not in dependencies.

**Comment by nknapp** [comment]
Oops... Didn't happen to me, because I always ran the program from the checked-out git repo (with dev-dependencies installed). Thank you for bringing my attention to it.

Fixed in 1.3.4
