### ISSUE TITLE
it shows NaN

### ISSUE THREAD

**Issue by mysticatea** [nknapp/analyze-module-size#5]
Hello.

I ran this tool to get dependency sizes, but it showed `NaN` at all. What did I go wrong?

![image](https://user-images.githubusercontent.com/1937871/32309083-976b16ee-bfcc-11e7-84cd-5682ad959d40.png)

> Versions:
>
> - OS: Windows 7
> - Node.js: 8.9.0
> - npm: 5.5.1

**Comment by nknapp** [comment]
I'm not sure
 Never tried it with node 8 and never on Windows. I'd have to look, but not before the weekend.

**Comment by nknapp** [comment]
It works with Node 8. Can anybody else try with windows?

**Comment by nknapp** [comment]
This is now fixed in the current release
