### ISSUE TITLE
'Could not find /fsevents' - failure to cope with (validly) missing modules

### ISSUE THREAD

**Issue by mbwhite** [nknapp/analyze-module-size#8]
For some reason my application turns out to be 64mb - so thought I'd use this tool to try and work our which dependancy is the problem. 

```
 analyze-module-size                                                                                                                         
dependencies found: 687 ...done
Loading dependency details: =============================================================================================== /yargs
Connecting dependency graph
Error: Could not find "/fsevents"
```

Not sure if this `analyze-module-size` or something else that requires fsevents.

**Comment by mbwhite** [comment]
The problem is clearer, https://www.npmjs.com/package/fsevents is the module in question which is OSX specific. As I'm on Linux, this isn't installed - so therefore it isn't going to be found. 

So not a bug as such but an enhancement to cope with modules that aren't present validly so.

**Comment by nknapp** [comment]
The fact that `fsevents` is not enough  to get this error message. The error is thrown [in src/Package.js](https://github.com/nknapp/analyze-module-size/blob/master/src/Package.js#L43) when a dependency claims to be `_requiredBy` this package.

There must be a dependency that has `_requiredBy: [ '/fsevents' ]` in its package.json. Is your package  using `lerna` like the `composer`?

**Comment by nknapp** [comment]
I you like, you can submit a PR that does not throw an exception but logs a warning instead.
But, it feels like there should be a warning logged (like `xxxx is required by fsevents, but there is no such package`.

**Comment by nknapp** [comment]
I have added a commit to the branch, that collects missing dependents. It is not yet writting to the output, but it's a first step.
